### ISSUE TITLE
Plugin Radio does not recognize AAC+ radio streams

### ISSUE THREAD

**Issue by Shillos** [ItsOnlyBinary/my-kiwiirc-plugins#2]
Hi just wanted to know if there's a way to make aac streams work on this plugin if possible by direct linking to m3u playlist that are mostly used by mp3 / aac or other. I tested it on my kiwi chat, but no luck to work. Would be appreciated if you could look into this. I tried on my radio station using the direct link from my server http://64.71.79.181:4272/live.m3u but nothing could be heard on the plugin.

**Comment by Shillos** [comment]
If there is a possibility to have a way implementing aac in the player would be appreciated. I have found something that might help using howler.js might help to make it a better player or similar? https://medium.com/crowdbotics/build-your-own-radio-streaming-app-with-howler-js-637f929decc0

**Comment by ItsOnlyBinary** [comment]
The ability to play formats is limited by the browser. mp3 seems to be the best format to use from my limited testing (ff, chrome, ie11, edge).

I did initially try to use howler but ran into issues with chrome which have since been fixed, but howler uses html5 audio for audio streams so wouldnt add format support to the browser, it would also mean going back to the older webpack version and loosing the current simplicity and ease of modification.

**Comment by Shillos** [comment]
Well I found a workaround for now. I added a parallel stream to my centova cast icecast 2 mount point and made it to work with mp3 streaming. I think that's the only workaround i could do for now, while i do hate mp3 streaming and always preferred aac+. But if there will ever be a way to make it work with aac and opus would be appreciated! :-)
